from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from datetime import datetime, timezone

# NOTE: User dataclass retained for legacy downloader/submissions compatibility.
# Active auth uses PIN-based flow, but the UserRepository adapter still maps this model.

@dataclass
class User:
    id: str
    google_id: Optional[str]
    email: str
    name: str
    is_active: bool = True
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class Tag:
    id: str
    category: str
    name_translations: Dict[str, str]  # e.g., {"en": "Pothole", "es": "Bache"}
    is_active: bool = True

    def get_localized_name(self, lang: str = "es") -> str:
        """Returns the translated tag name, falling back to Spanish if missing."""
        return self.name_translations.get(lang, self.name_translations.get("es", "Unknown"))

@dataclass
class SubmissionItem:
    id: str
    submission_id: str
    tag_id: str
    item_type: str  # "image", "text", "price_data"
    content_payload: Dict[str, Any]  # Flexible payload for file paths or OCR JSON

@dataclass
class Submission:
    id: str
    user_id: str
    latitude: float
    longitude: float
    device_timestamp: datetime
    status: str = "pending"
    server_timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    items: list[SubmissionItem] = field(default_factory=list)


@dataclass
class Report:
    """New data model for campo-ciudadano field reports."""
    id: str
    client_id: str                    # UUID generated by the client device
    latitude: float
    longitude: float
    gps_accuracy: Optional[float]     # metres
    barrio: Optional[str]             # Selected neighbourhood name
    event_tags: List[str]             # e.g. ["per.1", "bar.34"]
    notes: str
    device_timestamp: datetime
    server_timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    photo_filenames: List[str] = field(default_factory=list)  # filenames in STORAGE_DIR
    status: str = "received"
